### ISSUE TITLE
Incomplete libraries included in third-party documentation

### ISSUE THREAD

**Issue by Charlie0257** [JiangBowen0008/HACManPP#1]
@JiangBowen0008 Thanks for your great work!

When I try the following command, I found robosuite is not included :(
```
git clone 
git submodule update --init --recursive
```

How can I avoid this problem?

By the way, which version of `mujoco-py` do you use in this project?

Thanks for any help!

Best,
Charlie

**Comment by JiangBowen0008** [comment]
Hi Charile, thanks for your interest!

We have accidentally missed submodule links. They are now added back. Please let me know if the latest code fixes the problem.

**Comment by Charlie0257** [comment]
Thanks for your reply! It works now! ``

However, when I try `MUJOCO_PY_FORCE_CPU=1 python make_bin_vec_env.py`, the
error is
```
MUJOCO_PY_FORCE_CPU=1 python make_bin_vec_env.py
Traceback (most recent call last):
  File "make_bin_vec_env.py", line 15, in <module>
    from hacman.envs.sim_envs.base_env import RandomLocation
  File "/home/charlie/PycharmProjects/HACManPP/hacman/envs/__init__.py",
line 1, in <module>
    from .sim_envs import *
ModuleNotFoundError: No module named 'hacman.envs.sim_envs'
```

Could you update the corresponding files in the project?

Best,
Charlie

**Comment by yilin-wu98** [comment]
Sorry that we miss the sim_envs files. I just uploaded them.

**Comment by Charlie0257** [comment]
@yilin-wu98 Thanks for your great work!

However, when I try `MUJOCO_PY_FORCE_CPU=1 python make_bin_vec_env.py`, the
error is
```
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/hacman/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/charlie/anaconda3/envs/hacman/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charlie/PycharmProjects/HACManPP/third_party/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/home/charlie/PycharmProjects/HACManPP/third_party/stable-baselines3/stable_baselines3/common/env_util.py", line 82, in _init
    env = env_id(**env_kwargs)
  File "/home/charlie/PycharmProjects/HACManPP/hacman_bin/hacman_bin_env.py", line 54, in __init__
    BinEnv.__init__(self, **kwargs)
  File "/home/charlie/PycharmProjects/HACManPP/hacman_bin/bin_env.py", line 121, in __init__
    assert os.path.exists(pose_file), "Pose file does not exist: {}".format(pose_file)
AssertionError: Pose file does not exist: /home/charlie/PycharmProjects/HACManPP/hacman_bin/data/housekeep_all/poses_variable_size_v1.pk
```

Could you update the corresponding files in the project?

Best,
Charlie

**Comment by yilin-wu98** [comment]
This issue is now fixed with the new uploaded folders that are ignored before.

**Comment by Charlie0257** [comment]
@yilin-wu98 Thanks for your help!

When I try `python scripts/launch.py ExpID=9999 ExpGroup=ms_stack_cube_test +experiments=ms_stack_cube cluster=local ++n_seeds=1`, the terminal output the following info but the program doesn't run :(
```
CUDA_VISIBLE_DEVICES=0 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_point --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 2 --target_update_interval 2 --name Exp9999-0-0-ms_stack_cube_test-ours --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-ours --ExpID 9999 > slurm_output/Exp9999-0-0_ms_stack_cube_test-ours.stdout


CUDA_VISIBLE_DEVICES=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo TD3 --egreedy 0.1 --action_mode flat --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-1-0-ms_stack_cube_test-RAPS_TD3_pcd --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-RAPS_TD3_pcd --ExpID 9999 > slurm_output/Exp9999-1-0_ms_stack_cube_test-RAPS_TD3_pcd.stdout


CUDA_VISIBLE_DEVICES=2 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_primitive --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-2-0-ms_stack_cube_test-PP --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-PP --ExpID 9999 > slurm_output/Exp9999-2-0_ms_stack_cube_test-PP.stdout


screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=0 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_point --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 2 --target_update_interval 2 --name Exp9999-0-0-ms_stack_cube_test-ours --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-ours --ExpID 9999 > slurm_output/Exp9999-0-0_ms_stack_cube_test-ours.stdout'
& screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo TD3 --egreedy 0.1 --action_mode flat --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-1-0-ms_stack_cube_test-RAPS_TD3_pcd --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-RAPS_TD3_pcd --ExpID 9999 > slurm_output/Exp9999-1-0_ms_stack_cube_test-RAPS_TD3_pcd.stdout'
& screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=2 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_primitive --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-2-0-ms_stack_cube_test-PP --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-PP --ExpID 9999 > slurm_output/Exp9999-2-0_ms_stack_cube_test-PP.stdout'
```
Could you give me some advice?

Best,
Charlie

**Comment by zichunxx** [comment]
> @yilin-wu98 Thanks for your help!
> 
> When I try `python scripts/launch.py ExpID=9999 ExpGroup=ms_stack_cube_test +experiments=ms_stack_cube cluster=local ++n_seeds=1`, the terminal output the following info but the program doesn't run :(
> 
> ```
> CUDA_VISIBLE_DEVICES=0 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_point --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 2 --target_update_interval 2 --name Exp9999-0-0-ms_stack_cube_test-ours --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-ours --ExpID 9999 > slurm_output/Exp9999-0-0_ms_stack_cube_test-ours.stdout
> 
> 
> CUDA_VISIBLE_DEVICES=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo TD3 --egreedy 0.1 --action_mode flat --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-1-0-ms_stack_cube_test-RAPS_TD3_pcd --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-RAPS_TD3_pcd --ExpID 9999 > slurm_output/Exp9999-1-0_ms_stack_cube_test-RAPS_TD3_pcd.stdout
> 
> 
> CUDA_VISIBLE_DEVICES=2 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_primitive --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-2-0-ms_stack_cube_test-PP --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-PP --ExpID 9999 > slurm_output/Exp9999-2-0_ms_stack_cube_test-PP.stdout
> 
> 
> screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=0 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_point --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 2 --target_update_interval 2 --name Exp9999-0-0-ms_stack_cube_test-ours --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-ours --ExpID 9999 > slurm_output/Exp9999-0-0_ms_stack_cube_test-ours.stdout'
> & screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=1 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo TD3 --egreedy 0.1 --action_mode flat --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-1-0-ms_stack_cube_test-RAPS_TD3_pcd --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-RAPS_TD3_pcd --ExpID 9999 > slurm_output/Exp9999-1-0_ms_stack_cube_test-RAPS_TD3_pcd.stdout'
> & screen -dm bash -c 'conda activate hacman; CUDA_VISIBLE_DEVICES=2 OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 python scripts/run.py --env stack_cube --max_episode_steps 10 --parallel_env --train_n_envs 60 --gradient_steps 80 --object_pcd_size 400 --background_pcd_size 400 --background_clip_radius 0.2 --voxel_downsample_size 0.002 --reward_scale 0.2 --clamp_critic_max 0 --clamp_critic_min -20 --reward_aggregation average --location_model_temperature 2 --gamma 0.99 --initial_timesteps 10000 --action_noise 0.1 --bg_mapping_mode bbox --end_on_reached --pad_rewards --primitives poke pick_n_lift_fixed place move open_gripper --algo MultiTD3 --egreedy 0.1 --location_model argmaxQ --action_mode per_primitive --feature_mode points --preprocessing_fn flow --learning_rate 0.0001 --batch_size 64 --actor_update_interval 1 --target_update_interval 1 --name Exp9999-2-0-ms_stack_cube_test-PP --dirname logs/hacman --seed 0 --ExpGroup Exp9999-ms_stack_cube_test --ExpVariant Exp9999-ms_stack_cube_test-PP --ExpID 9999 > slurm_output/Exp9999-2-0_ms_stack_cube_test-PP.stdout'
> ```
> 
> Could you give me some advice?
> 
> Best, Charlie

Same issue. I'm not familiar with `hydra`, but I think `run.py` should be the file to start the training.

**Comment by yilin-wu98** [comment]
Please follow the instruction I put in the readme. If you are running it locally, you need to copy and paste the output to your terminal and run the experiments. For example, the output here shows the three experiments with different seeds. launch.py is the file that converts the complicated config into a command with run.py. You need to run the command with run.py in terminal to start the experiments.

**Comment by Charlie0257** [comment]
@yilin-wu98 Thanks for your reply!
