### ISSUE TITLE
Miss data folder 

### ISSUE THREAD

**Issue by zichunxx** [JiangBowen0008/HACManPP#2]
Hi! Thanks for your great sharing!

I tried the command `MUJOCO_PY_FORCE_CPU=1 python make_bin_vec_env.py` in instructions and met a missing file error: 

```
assert os.path.exists(pose_file), "Pose file does not exist: {}".format(pose_file)
AssertionError: Pose file does not exist: PATH_TO/HACManPP/hacman_bin/data/housekeep_all/poses_variable_size_v1.pk
```

Did you forget to upload a folder?

Thanks!

**Comment by yilin-wu98** [comment]
Thanks for bring this question! When we migrate the repo, some folders are ignored. We have fixed this and added the missing folders. Now it should be working properly with MUJOCO_PY_FORCE_CPU=1 python make_bin_vec_env.py.

**Comment by zichunxx** [comment]
Thanks for your quick response!
